version: "3"

services:
  frontend:
    build:
      context: .

    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://localhost:8000
    restart: always

  backend:
    build:
      context: ./backend

    ports:
      - "8000:8000"
    # Add any environment variables your backend needs
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    # Add volumes if needed
    # volumes:
    #   - ./backend/data:/app/data
